### PR TITLE
fix: orgStatus & orgType as valid skos:Concept

### LINKED ISSUE #104: org-type og org-status er ikke valid ihht SKOS-AP-NO-Begrep

### PR DESCRIPTION
**Pull request by NilsOveTen**
resolves #104

### CODE REVIEW

**Review by stigbd — APPROVED** [review]

File: src/main/kotlin/no/brreg/informasjonsforvaltning/organizationcatalogue/jena/JenaUtils.kt [hunk 1]
```diff
@@ -103,9 +99,9 @@ private fun Resource.addPreferredNames(preferredNames: PrefLabel?): Resource {
 
 private fun Resource.addOrgStatus(orgStatus: OrgStatus?): Resource {
     when (orgStatus) {
-        null -> addProperty(ROV.orgStatus, BRSKOS.NormalAktivitet)
-        OrgStatus.NORMAL -> addProperty(ROV.orgStatus, BRSKOS.NormalAktivitet)
-        else -> addProperty(ROV.orgStatus, BRSKOS.Avviklet)
+        null -> addProperty(ROV.orgStatus, ORGSTATUS.NormalAktivitet)
```
Comment (oyvindis) [inline src/main/kotlin/no/brreg/informasjonsforvaltning/organizationcatalogue/jena/JenaUtils.kt:100]: Kan denne forenkles slik:
null, OrgStatus.NORMAL -> addProperty(ROV.orgStatus, ORGSTATUS.NormalAktivitet)

**Review by oyvindis — APPROVED** [review]

File: src/main/kotlin/no/brreg/informasjonsforvaltning/organizationcatalogue/jena/JenaUtils.kt (hunk 1 above)
Comment (NilsOveTen) [reply src/main/kotlin/no/brreg/informasjonsforvaltning/organizationcatalogue/jena/JenaUtils.kt]: j
3fed98f
